### ISSUE TITLE
💗 It!  There's much much more than what the Screenshot shows....

### ISSUE THREAD

**Issue by PySimpleGUI** [DAFEX6390/python-notepad#1]
I am so pleased to see a screenshot in your readme!  Grabbed my attention and I'm SURE many others.

It wasn't until I took a quick look in your code that I saw the sophistication is much more than your modest Readme conveys.

A GIF file of you going through menus, showing off the advanced features would be an excellent addition.  I use ShareX to get these kinds of GIFs made.  

If you've not tried the `psgcompiler` project to make an EXE file, I would be interested in your feedback on it.  It's the way I've tried to make creating distributable PySimpleGUI programs simpler to make.  I've not been very successful in getting the word out on this tool despite it being in the docs.

I really like what you've done!  Keep building!   
![image](https://user-images.githubusercontent.com/46163555/152352991-0fc883ef-6a23-4a83-998b-e5a5d8937f0c.png)

**Comment by dfm18** [comment]
Ok, thanks for the suggestions 💙 💛

**Comment by PySimpleGUI** [comment]
I've never seen this before!  💙 💛

Brilliant!  I'm afraid I'm going to have to maybe steal these from you and put them inside PySimpleGUI  
![image](https://user-images.githubusercontent.com/46163555/152446065-5b4dc291-3890-4b2c-ba97-154b6f8bccb0.png)

There are 2 red hearts in PySimpleGUI, but no "Python hearts".

```python
import PySimpleGUI as sg

sg.Window('', [[sg.Im(sg.HEART_3D_BASE64), sg.Im(sg.HEART_FLAT_BASE64)]]).read()
```

![image](https://user-images.githubusercontent.com/46163555/152446207-4d216aa9-7061-433b-a4ea-765b449db0ef.png)


They're extra large so that you can subsample them down to the size you want:

```python
import PySimpleGUI as sg

sg.Window('', [[sg.Im(sg.HEART_3D_BASE64, subsample=2), sg.Im(sg.HEART_FLAT_BASE64, subsample=3)]]).read()
```

![image](https://user-images.githubusercontent.com/46163555/152446591-d0814bdf-acde-426d-a3d2-0ecab2300bf0.png)

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/152516959-3c5de61a-3bd3-4ffe-9f44-4381925c4bdb.png)

Thank you for the GIF!  Very nice and grabs attention.  And thank you for all the kind words and mentions in your readme.  I really appreciate you spreading the word.  Happy users create more happy users.

**Comment by dfm18** [comment]
Thank you for creating PySimpleGUI!! 💗

**Comment by PySimpleGUI** [comment]
Thank you for the hearts!

![pythonw_4gSz52JWUz](https://user-images.githubusercontent.com/46163555/152620944-fb29650c-8118-4c4d-87e9-d4ff0f12b221.gif)
